# Generated by Django 5.2.5 on 2025-08-17 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_theory_marks', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('pass_theory_marks', models.DecimalField(decimal_places=2, default=40, max_digits=5)),
                ('full_practical_marks', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('pass_practical_marks', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5)),
                ('has_practical', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.class')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='management.examination')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.subject')),
            ],
            options={
                'unique_together': {('examination', 'classroom', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='StudentOverallResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_subjects', models.IntegerField(default=0)),
                ('subjects_passed', models.IntegerField(default=0)),
                ('subjects_failed', models.IntegerField(default=0)),
                ('total_grade_points', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('overall_grade', models.CharField(blank=True, max_length=5)),
                ('total_marks_obtained', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_full_marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('overall_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_promoted', models.BooleanField(default=False)),
                ('extracurricular_grade', models.CharField(blank=True, max_length=10)),
                ('extracurricular_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overall_results', to='management.examination')),
                ('extracurricular_entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_extracurricular', to='management.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overall_results', to='management.student')),
            ],
            options={
                'unique_together': {('examination', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('practical_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, max_length=5)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('is_passed', models.BooleanField(default=False)),
                ('is_theory_passed', models.BooleanField(default=False)),
                ('is_practical_passed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_results', to='management.teacher')),
                ('exam_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResultManagement.examconfiguration')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='management.examination')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='management.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.subject')),
            ],
            options={
                'unique_together': {('examination', 'student', 'subject')},
            },
        ),
    ]
