# Generated by Django 5.2.5 on 2025-08-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
