# Generated by Django 5.2.5 on 2025-08-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_contact_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('grade', models.CharField(max_length=20)),
                ('section', models.CharField(blank=True, max_length=5, null=True)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('permanent_address', models.TextField()),
                ('temporary_address', models.TextField(blank=True, null=True)),
                ('student_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('guardian_contact', models.CharField(max_length=15)),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='documents/birth_certificates/')),
                ('transfer_certificate', models.FileField(blank=True, null=True, upload_to='documents/transfer_certificates/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
