# Generated by Django 5.2.5 on 2025-08-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_contact',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_contact',
            field=models.CharField(default=73424342342, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='transfer_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
