# Generated by Django 5.2.5 on 2025-08-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_teacher_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='linked_profile',
            new_name='linkedin_profile',
        ),
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='citizenship_back',
            field=models.FileField(blank=True, null=True, upload_to='teacher_citizenship_back/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='citizenship_front',
            field=models.FileField(blank=True, null=True, upload_to='teacher_citizenship_front/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='teacher_pan_cards/'),
        ),
    ]
