# Generated by Django 5.2.5 on 2025-08-10 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_examination_extracurriculargrade_studentexammark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examination',
            unique_together={('name', 'classroom', 'subject')},
        ),
    ]
