# Generated by Django 5.2.5 on 2025-08-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_examination_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('classroom', 'subject', 'teacher')},
        ),
    ]
