# Generated by Django 5.2.5 on 2025-08-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_classsubject_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examination',
            unique_together={('name', 'subject', 'date')},
        ),
        migrations.AddField(
            model_name='examination',
            name='classrooms',
            field=models.ManyToManyField(related_name='examinations', to='management.class'),
        ),
        migrations.RemoveField(
            model_name='examination',
            name='classroom',
        ),
    ]
