# Generated by Django 5.2.5 on 2025-08-10 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_alter_examination_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examination',
            unique_together={('name', 'subject')},
        ),
    ]
