# Generated by Django 5.2.5 on 2025-08-10 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_examination_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
    ]
