# Generated by Django 5.2.5 on 2025-08-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_remove_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
