# Generated by Django 5.2.5 on 2025-08-17 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_name', models.CharField(max_length=255)),
                ('exam_time', models.CharField(blank=True, max_length=100, null=True)),
                ('note_above', models.TextField(blank=True, null=True)),
                ('note_below', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamRoutineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('class_name', models.CharField(max_length=80)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ExamManagement.examroutine')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.subject')),
            ],
            options={
                'ordering': ['exam_date', 'class_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentExamRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_remarks', to='management.class')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_remarks', to='management.teacher')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_remarks', to='management.examination')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_remarks', to='management.student')),
            ],
            options={
                'unique_together': {('classroom', 'student', 'examination')},
            },
        ),
    ]
