# Generated by Django 5.2.5 on 2025-08-11 17:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examroutineitem',
            options={'ordering': ['exam_date', 'class_name']},
        ),
        migrations.RenameField(
            model_name='examroutine',
            old_name='note',
            new_name='note_above',
        ),
        migrations.RemoveField(
            model_name='examroutine',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='examroutine',
            name='examination',
        ),
        migrations.AddField(
            model_name='examroutine',
            name='exam_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='examroutine',
            name='examination_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examroutine',
            name='note_below',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examroutineitem',
            name='class_name',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='examroutineitem',
            unique_together={('routine', 'exam_date', 'class_name')},
        ),
    ]
