# Generated by Django 5.2.5 on 2025-08-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamManagement', '0002_alter_examroutineitem_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examroutineitem',
            unique_together=set(),
        ),
    ]
