# Generated by Django 5.2.5 on 2025-08-11 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamManagement', '0003_alter_examroutineitem_unique_together'),
        ('management', '0017_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExamRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_remarks', to='management.class')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_remarks', to='management.teacher')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_remarks', to='management.examination')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_remarks', to='management.student')),
            ],
            options={
                'unique_together': {('classroom', 'student', 'examination')},
            },
        ),
    ]
